name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Release build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: poodle
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            exe: poodle
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            exe: poodle
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabi
            exe: poodle
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            exe: poodle
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            exe: poodle
          - os: macos-latest
            target: x86_64-apple-darwin
            exe: poodle
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: poodle.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            exe: poodle.exe
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Test
        run: cargo test --release --target ${{ matrix.target }} --verbose --all
      - name: Build
        run: cargo build --release --target ${{ matrix.target }} --verbose --all
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: poodle-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.exe }}
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: zip
          filename: poodle-${{ matrix.target }}.zip
          directory: target/${{ matrix.target }}/release/
          path: ${{ matrix.exe }}
      - name: Release 🚀
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.target }}/release/poodle-${{ matrix.target }}.zip
          generate_release_notes: true
          draft: true
