name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --all --release
  release_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: poodle
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            exe: poodle
            target: x86_64-apple-darwin
          - os: windows-latest
            exe: poodle.exe
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --verbose --all --release
    - uses: actions/upload-artifact@v2
      with:
        name: poodle-${{ matrix.target }}
        path: target/release/${{ matrix.exe }}
