name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --all --release
  release_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all --release
    - name: Tar files
      run: tar -cvf ${{ matrix.os }}_build.tar target/release/poodle
    - name: Archive release binary
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          ${{ matrix.os }}_build.tar
        retention-days: 2
  release_build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --all --release
    - name: Archive release binary
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          target/release/poodle.exe
        retention-days: 2
