name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose --all --release
  release_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            exe: poodle
          - os: macos-latest
            target: x86_64-apple-darwin
            exe: poodle
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe: poodle.exe
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: cargo test --verbose --all --release
    - name: Build
      run: cargo build --verbose --all --release
    - uses: actions/upload-artifact@v3
      with:
        name: poodle-${{ matrix.target }}
        path: target/release/${{ matrix.exe }}
        retention-days: 2
